# Generated by Django 5.0.14 on 2026-08-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QrGenerationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField()),
                ('fg_color', models.CharField(max_length=7)),
                ('bg_color', models.CharField(max_length=7)),
                ('has_logo', models.BooleanField(default=False)),
                ('export_format', models.CharField(choices=[('PNG', 'PNG'), ('SVG', 'SVG')], default='PNG', max_length=3)),
                ('resolution', models.PositiveIntegerField(default=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
