# Generated by Django 5.0.14 on 2026-08-17 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('generator', '0001_initial'),
        ('templates_qr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrgenerationhistory',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='templates_qr.qrtemplate'),
        ),
    ]
