# Generated by Django 5.0.14 on 2026-08-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QrTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fg_color', models.CharField(default='#000000', max_length=7)),
                ('bg_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('dot_style', models.CharField(choices=[('square', 'Square'), ('rounded', 'Rounded'), ('dots', 'Dots')], default='square', max_length=20)),
                ('error_correction', models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('Q', 'Quartile'), ('H', 'High')], default='H', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
